version: '3'
services:
  rpc_1:
    container_name: pid-wavesynth
    image: ddps:v2
    volumes:
      - .:/wavesynth_1
    ports:
    - 7900:7900
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  